spring:
  datasource:
    url: jdbc:mysql://localhost:3306/friend_finder?useUnicode=true
    username: root
    password: rootroot
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/liquibase/changelog.xml

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  mail:
    host: smtp.gmail.com
    username: finderfriend2023@gmail.com
    password: fmfvomabgtxtdjbe
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#Post path
post:
  upload:
    image:
      path: /Users/Spring Teamwork Website/friend-finder/src/main/java/com/friendfinder/images/posts/postImages/

  video:
    upload:
      image:
        path: /Users/Spring Teamwork Website/friend-finder/src/main/java/com/friendfinder/images/posts/videos/


#User profile
user:
  profile:
    picture:
      path: /Users/Spring Teamwork Website/friend-finder/src/main/java/com/friendfinder/images/profile/avatar/
    background-picture:
      path: /Users/Spring Teamwork Website/friend-finder/src/main/java/com/friendfinder/images/profile/background/

site:
  url: http://localhost:8080

server:
  error:
    path: /error

    whitelabel:
      enabled: false